### ISSUE TITLE
Add full path to `cytfm_pelion_policy.json`

### ISSUE THREAD

**Issue by ep1cman** [PelionIoT/mbed-os-example-pelion-psoc64#11]
In "Updating firmware" instruction 1. the user is told to edit the file "cytfm_pelion_policy.json" but is not told where to locate said file (`TARGET_CYTFM_064B0S2_4343W/policy/cytfm_pelion_policy.json`)

**Comment by cvasilak** [comment]
fixed in PR https://github.com/ARMmbed/mbed-os-example-pelion-armdevsummit/pull/10
