### ISSUE TITLE
[BUG] Device ID explanation

### ISSUE THREAD

**Issue by ep1cman** [PelionIoT/mbed-os-example-pelion-psoc64#15]
When trying to perform the device update I have to enter the device ID. It was not clear what this ID should be, I tried to use the serial number I used earlier on in the process but this lead to a stuck update campaign saying it had an invalid UUID.

The instructions should be updated to explain you can get this ID from: https://portal.mbedcloud.com/devices/list in the `Device ID` column

**Comment by cvasilak** [comment]
fixed in PR https://github.com/ARMmbed/mbed-os-example-pelion-armdevsummit/pull/10
