### ISSUE TITLE
Patch does not apply to MacOS

### ISSUE THREAD

**Issue by maclobdell** [PelionIoT/mbed-os-example-pelion-psoc64#3]
**Describe the bug**
  In the readme for CYTFM_...  at 
https://github.com/ARMmbed/mbed-os-example-pelion-armdevsummit/blob/armdevsummit/TARGET_CYTFM_064B0S2_4343W/README.md#building-and-running-the-example

It says that Mac OS is case-insensitive and requires applying a patch to the application. this is not true. It shouldn't be required because Mac is case-sensitive. However, I guess it does't hurt.

**Comment by moshe-shahar** [comment]
AFAIK, in Mac OS, user can choose the File System mode.

**Comment by maclobdell** [comment]
I see. thanks. I see that my file system is case-insensitive on Mac. my mistake.
