### ISSUE TITLE
Readme for CYTFM contains references to GCC_ARM

### ISSUE THREAD

**Issue by maclobdell** [PelionIoT/mbed-os-example-pelion-psoc64#5]
With the new instructions for Mbed Studio, the paths should be changed to /ARM/ and not /GCC_ARM

example, in this command
python inthex2bin.py BUILD/CYTFM_064B0S2_4343W/GCC_ARM/mbed-os-example-pelion_upgrade.hex

it should be 
python inthex2bin.py BUILD/CYTFM_064B0S2_4343W/ARMC6/mbed-os-example-pelion-armdevsummit_upgrade.hex

(also need to change references to the example application name, which is now mbed-os-example-pelion-armdevsummit)

**Comment by cvasilak** [comment]
fixed in PR https://github.com/ARMmbed/mbed-os-example-pelion-armdevsummit/pull/6
